
server:
  port: 7777
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "https://docs.spring.io"
#            allowedMethods:
#              - POST
#    gateway:
#      default-filters:
#        - AddResponseHeader= Access-Control-Allow-Origin, *
#        - AddResponseHeader= Access-Control-Allow-Methods, GET, POST, PUT, OPTIONS
#        - AddResponseHeader= Access-Control-Allow-Credentials, true
#        - AddResponseHeader= Access-Control-Allow-Headers, Accept,Accept-Encoding,Accept-Language,Connection,Content-Length,Content-Type,Host,Origin,Referer,User-Agent
    inetutils:
      ignored-interfaces:
        - VirtualBox Host-Only Network
        - VMware Network Adapter VMnet1
        - VMware Network Adapter VMnet8
    bootstrap:
      enable: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: pplax-gateway

springdoc:
  swagger-ui:
    use-root-path: true
#    urls:
#      - name: pplax-article
#        url: /v3/api-docs/pplax-article
#      - name: pplax-file
#        url: /v3/api-docs/pplax-file