spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    inetutils:
      ignored-interfaces:
        - VirtualBox Host-Only Network
        - VMware Network Adapter VMnet1
        - VMware Network Adapter VMnet8
    bootstrap:
      enable: true

springdoc:
  swagger-ui:
    use-root-path: true
#    urls:
#      - name: pplax-article
#        url: /v3/api-docs/pplax-article
#      - name: pplax-file
#        url: /v3/api-docs/pplax-file