server:
  port: 8088
  compression:
    enabled: false
spring:
  main:
    allow-circular-references: true
#pplax:
#  amqp:
#    exchanges:
#      # 发送邮件的交换机
#      - exchange: pplax.send.email.common.exchange
#        exchange-type: topic
#        dead-letter-exchange: pplax.send.email.dead.letter.exchange
#        dead-letter-exchange-type: direct
#        queues:
#          # 发送html邮件
#          - queue: send.html.mail.queue
#            dead-letter-queue: send.html.mail.dead.letter.queue
#            routing-key: send.html.amil.routing
#            dead-letter-routing-key: send.html.mail.dead.letter.routing
#
#          - queue: send.simple.text.mail.queue
#            dead-letter-queue: send.simple.text.mail.dead.letter.queue
#            routing-key: send.simple.text.mail.routing
#            dead-letter-routing-key: send.simple.text.mail.dead.letter.routing
#            # 发送错误消息的交换机
#      - exchange: pplax.send.mistake.exchange
#        exchange-type: topic
#        dead-letter-exchange: pplax.send.mistake.dead.letter.exchange
#        dead-letter-exchange-type: direct
#        queues:
#          - queue: pplax.mistake.queue
#            dead-letter-queue: pplax.mistake.dead.letter.queue
#            routing-key: pplax.mistake.routing.key
#            dead-letter-routing-key: pplax.mistake.dead.letter.routing.key
#              # 发送操作用户数据的交换机
#      - exchange: pplax.send.operate.user.exchange
#        exchange-type: topic
#        dead-letter-exchange: pplax.send.operate.user.dead.letter.exchange
#        dead-letter-exchange-type: direct
#        queues:
#          - queue: pplax.operate.user.binding.email.queue
#            dead-letter-queue: pplax.operate.user.binding.email.dead.letter.queue
#            routing-key: pplax.operate.user.binding.email.routing
#            dead-letter-routing-key: pplax.operate.user.binding.email.dead.letter.routing
#
#          - queue: pplax.operate.user.lock.account.queue
#            dead-letter-queue: pplax.operate.user.lock.account.dead.letter.queue
#            routing-key: pplax.operate.user.lock.account.routing.key
#            dead-letter-routing-key: pplax.operate.user.lock.account.dead.letter.routing.key
#
#          - queue: pplax.update.role.permission.queue
#            dead-letter-queue: pplax.update.role.permission.dead.letter.queue
#            routing-key: pplax.update.role.permission.routing.key
#            dead-letter-routing-key: pplax.update.role.permission.dead.letter.routing
#
#          - queue: pplax.update.white.url.queue
#            dead-letter-queue: pplax.update.white.url.dead.letter.queue
#            routing-key: pplax.update.white.url.routing.key
#            dead-letter-routing-key: pplax.update.white.url.dead.letter.routing
#              # 发送评论的交换机
#      - exchange: pplax.send.comment.exchange
#        exchange-type: topic
#        dead-letter-exchange: pplax.send.comment.dead.letter.exchange
#        dead-letter-exchange-type: direct
#        queues:
#          - queue: pplax.PAGE.comment.queue
#            dead-letter-queue: pplax.PAGE.comment.dead.letter.queue
#            routing-key: pplax.PAGE.routingKey
#            dead-letter-routing-key: pplax.PAGE.comment.dead.letter.routingKey
#    default-max-length: 25
#    default-ttl: 6000
#pplax:
#  default:
#    user:
#      navbar-info: '[{"name":"首页","url":"/user/1522074993315815424","icon":"fa:home","children":[]},{"name":"友情链接","url":"/friendLink/1522074993315815424","icon":"fa:paper-plane","children":[]},{"name":"关于","url":"/about/1522074993315815424","icon":"fa:pagelines","outLink":false,"children":[]},{"name":"说说1","url":"/shareSpace/1522074993315815424","icon":"fa:comments-o","children":[]},{"name":"说说2","url":"/shareSpace-page/1522074993315815424","icon":"fa:comments-o","children":[]},{"name":"时间轴","url":"/archive/1522074993315815424","icon":"fa:hourglass-3","children":[]},{"name":"相册","url":"/photo/1522074993315815424","icon":"fa:image","children":[]},{"name":"标签","url":"/tag/1522074993315815424/","icon":"mdi:abugida-thai","children":[]},{"name":"分类","url":"/category/1522074993315815424","icon":"mdi:alarm-bell","outLink":false,"children":[]},{"name":"评论","url":"/comment/1522074993315815424","icon":"fa:comments","outLink":false,"children":[]},{"name":"说说","url":"","icon":"fa:comments","outLink":false,"children":[]}]'
#      page-info: '[{"name":"首页","url":"/user/1522074993315815424","icon":"fa:home","children":[]},{"name":"友情链接","url":"/friendLink/1522074993315815424","icon":"fa:paper-plane","children":[]},{"name":"关于","url":"/about/1522074993315815424","icon":"fa:pagelines","outLink":false,"children":[]},{"name":"说说1","url":"/shareSpace/1522074993315815424","icon":"fa:comments-o","children":[]},{"name":"说说2","url":"/shareSpace-page/1522074993315815424","icon":"fa:comments-o","children":[]},{"name":"时间轴","url":"/archive/1522074993315815424","icon":"fa:hourglass-3","children":[]},{"name":"相册","url":"/photo/1522074993315815424","icon":"fa:image","children":[]},{"name":"标签","url":"/tag/1522074993315815424/","icon":"mdi:abugida-thai","children":[]},{"name":"分类","url":"/category/1522074993315815424","icon":"mdi:alarm-bell","outLink":false,"children":[]},{"name":"评论","url":"/comment/1522074993315815424","icon":"fa:comments","outLink":false,"children":[]},{"name":"说说","url":"","icon":"fa:comments","outLink":false,"children":[]}]'
#      welcome-article: '# 这是欢迎页'


